config/routes.rb
Rails.application.routes.draw do

  resources :articles
  root 'articles#index'
  get '/signup' => 'users#new'
  resources :users
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy', as: :logout

  # get '/profile' => 'users#show'
  # get '/profile' => 'users#edit'
  get '/profile' => 'users#edit', as: :edit
  post '/profile' => 'users#update', as: :update

  # get 'users/new'
  # get 'sessions/new'
  # get 'articles/index'
  # get 'articles/show'
  # get 'articles/new'
  # get 'articles/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :require_login
  helper_method :logged_in?

  def logged_in?
    current_user != nil
  end
  

  def require_user
    redirect_to '/login' unless current_user
  end


  
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :author, :body)
    end

    def require_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to '/login' # halts request cycle
      end
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end 
  end 

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
 
    if @user.save
      redirect_to '/'
    else
      render '/signup'
    end
  end

  def edit
    @user = current_user
  end

  def update
    if current_user.update user_params
      redirect_to '/'
      # do something
    else
      render :edit
    end
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password)
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="update-article">
  <div class="container article">

    <%= form_for(@article) do |f| %>    
      <%= f.text_field :title , :maxlength => 255 %>
      <%= f.text_field :author, :maxlength => 255 %>
      <%= f.text_area :body , :maxlength => 10000 %>

      <%= f.submit "Save", :class => "btn save" %>
    <% end %>

  </div>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <div class=" container article">
    <p class="date"><%= article.created_at.strftime('%b %d') %></p>
    <!-- http://stackoverflow.com/questions/1086360/how-do-i-wrap-link-to-around-some-html-ruby-code -->
    <%= link_to(article) do %>
      <h2><%= article.title %></h2>
    <% end %>
    <p class="author">by <%= article.author %></p>
    <p class="article_content"><%= simple_format(truncate(article.body , :length => 140), class: 'article_content') %></p>
  </div>

<% end %>

<div class="container article">
  <%= link_to "Create new article", new_article_path(), :class => "btn new" %>
</div>

app/views/articles/new.html.erb
<div class="container article">

<%= form_for(@article) do |f| %>    
  <%= f.text_field :title %>
  <%= f.text_field :author %>
  <%= f.text_area :body %>

  <%= f.submit "CREATE", :class => "btn create" %>
<% end %>
</div>

app/views/articles/show.html.erb
<div class="container article">
    <p class="date"><%= @article.created_at.strftime('%b %d') %></p>
    <h2><%= @article.title %></h2>
    <p class="author">by <%= @article.author %></p>
    <p class="article_content"><%= simple_format(@article.body, class: 'article_content') %></p>
    <br/>

    <%= link_to 'Edit', edit_article_path(), :class => "btn edit" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newstand</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700|Roboto:100,400,500,700&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header>
      <div class="container-fluid">
        <div class="row">

          <div class="col-md-8 col-lg-6">
            <%= link_to(root_path) do %>
              <h1><span class="dark">n</span>ewstand</h1>
            <% end %>
          </div>

          <div class="col-md-4 col-lg-6">
            <div class="nav">
              <% if current_user %> 
                <ul> 
                  <li class="block"><%= current_user.email %></li> 
                  <li><%= link_to "Profile", '/profile', :class => 'btn' %></li>
                  <li><%= link_to "Log out", logout_path, :method => "delete", :class => 'btn' %></li> 
                </ul> 
              <% else %> 
                <ul> 
                  <li><%= link_to "Login", '/login', :class => 'btn' %></li> 
                  <li><%= link_to "Signup", '/signup', :class => 'btn' %></li> 
                </ul> 
              <% end %>
            </div>
          </div>
        </div>
               
      </div>
    </header>

    <main>

      <%= yield %>

    </main>

  </body>
</html>

app/views/users/edit.html.erb
<div class="container signup">

<%= form_for(@user) do |f| %>

	<%= f.text_field :first_name, :placeholder => "First name", :maxlength => 15 %><br />
	<%= f.text_field :last_name, :placeholder => "Last name", :maxlength => 15 %><br />
	<%= f.email_field :email, :placeholder => "Email", :maxlength => 128 %><br />
	<%= f.password_field :password, :placeholder => "Password", :maxlength => 128 %><br />

	<%= f.submit "Update", :class => "btn" %>

<% end %>

</div>

app/views/users/new.html.erb
<div class="container signup">


<%= form_for(@user) do |f| %>

	<%= f.text_field :first_name, :placeholder => "First name", :maxlength => 15 %><br />
	<%= f.text_field :last_name, :placeholder => "Last name", :maxlength => 15 %><br />
	<%= f.email_field :email, :placeholder => "Email", :maxlength => 128 %><br />
	<%= f.password_field :password, :placeholder => "Password", :maxlength => 128 %><br />

	<%= f.submit "SignUp", :class => "btn" %>

<% end %>

</div>

app/views/users/show.html.erb
<div class="container signup">

<%= form_for(@user) do |f| %>

	<%= f.text_field :first_name, :placeholder => "First name" %><br />
	<%= f.text_field :last_name, :placeholder => "Last name" %><br />
	<%= f.email_field :email, :placeholder => "Email" %><br />
	<%= f.password_field :password, :placeholder => "Password" %><br />

	<%= f.submit "Update", :class => "btn" %>

<% end %>

</div>